name: workflow-cd

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  workflow-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/install-requirements
        with:
          who-to-greet: 'workflow-cd'

      - name: unit-tests
        run: echo "unit-tests passed"

      - name: Build docker image
        run: echo "docker image built"
