name: workflow-ci

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  workflow-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/install-requirements
        with:
          who-to-greet: 'workflow-ci'

      - name: unit-tests
        run: echo "unit-tests passed"

      - uses: ./.github/actions/docker-build
