name: workflow-ci-cd

on:
  push:
    branches:
      - 'master'
      - 'deploy-*'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  workflow-ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/install-requirements
        with:
          who-to-greet: 'workflow-ci'

      - name: unit-tests
        run: echo "unit-tests passed"

      - uses: ./.github/actions/docker-build

      - name: push latest image to docker hub
        run: echo "push latest image to docker hub"

      - name: push released image to docker hub
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "push released image ${GITHUB_REF:10} to docker hub"
